# Generated by Django 4.1.5 on 2023-02-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorry',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sedan',
            name='owner',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.owner'),
        ),
    ]
