# Generated by Django 4.1.5 on 2023-02-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TollStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextnode_distance', models.IntegerField(default=0)),
                ('nextnode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='maps.node')),
                ('node', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.node')),
                ('prevnode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='maps.node')),
            ],
        ),
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=5000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ispaid', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('toll_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolls.tollstation')),
            ],
        ),
    ]
