# Generated by Django 4.1.5 on 2023-02-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0001_initial'),
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollviolation',
            name='car',
        ),
        migrations.AddField(
            model_name='tollviolation',
            name='toll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tolls.toll'),
        ),
    ]
