# Generated by Django 4.1.5 on 2023-02-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0001_initial'),
        ('violations', '0002_remove_tollviolation_car_tollviolation_toll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollviolation',
            name='toll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolls.toll'),
        ),
    ]
